services:
  # ────────────────────────────────────────
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: helical-backend
    volumes:
      - ./backend/data:/app/data      # datasets + SQLite
    environment:
      - HELICAL_DATA_DIR=/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped

  # ────────────────────────────────────────
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: dev  # <-- use dev stage
    container_name: helical-frontend
    ports:
      - "3000:3000"                        # host:container
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  worker:
    build: ./backend
    command: celery -A app.worker.celery_app worker --loglevel=info --concurrency=1
    depends_on:
      - redis
      - backend
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - ./backend/data:/app/data
  
  redis:
    image: redis:7
    container_name: helical-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
  flower:
    build: ./backend
    container_name: helical-flower
    command: celery -A app.worker.celery_app flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - backend

volumes:
  helical_data:      

                     # named volume keeps uploads + DB