
services:
  # ────────────────────────────────────────
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: helical-backend
    volumes:
      - helical_data:/app/data           # datasets + SQLite
    environment:
      - HELICAL_DATA_DIR=/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped

  # ────────────────────────────────────────
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: dev  # <-- use dev stage
    container_name: helical-frontend
    ports:
      - "3000:3000"                        # host:container
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  helical_data:                           # named volume keeps uploads + DB